apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aceest
      canary: "true"
  template:
    metadata:
      labels:
        app: aceest
        canary: "true"
    spec:
      containers:
      - name: aceest
        image: <REGISTRY>/aceest-fitness:canary
        ports:
        - containerPort: 5000