apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest
      version: green
  template:
    metadata:
      labels:
        app: aceest
        version: green
    spec:
      containers:
      - name: aceest
        image: <REGISTRY>/aceest-fitness:green
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10